config/routes.rb
Conversation::Application.routes.draw do

  resources :items do
      resources :tweets
  end

end

app/models/cat.rb
class Cat < ActiveRecord::Base

  # comment
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
    has_many:tweets, :dependent => :destroy
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :item
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

    def index
        @items = Item.all(:order =>'created_at DESC')
    end

    def new
        @item = Item.new
    end

    def create
        @item = Item.new(params[:item])
        if @item.save
            redirect_to items_path
        else
            render action: 'new'
        end
    end

    def edit
        @item = Item.find(params[:id])
        @tweets = Tweet.all(:order =>'created_at DESC')
        @new_tweet = Tweet.new
    end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    
    def index
        @tweets = Tweet.all(:order => 'created_ad DESC')
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/items/edit.html.erb
# encoding: utf-8

<table id="new_table" border="0">
  <tr><td><font color="blue">タイトル</font></td></tr>
</table>
<table id="new_table" border="0">
  <tr><td><%= @item.title %> [確度：<%= @item.reliability %>]</td></tr>
  <tr><td>&nbsp;</td></tr>
</table>

<table id="new_table" border="0">
  <tr><td><font color="blue">ボード</font></td></tr>
</table>
<table id="new_table" border="1" style="height:80px;">
  <tr><td>※ここに画像（写真）のっけたりフリーハンドでいろいろ書けたりする。</td></tr>
</table>
<br>

<table id="new_table" border="0">
  <tr><td><font color="blue">概要</font></td></tr>
</table>
<table id="new_table" border="1" style="height:80px;">
  <tr><td><%= @item.overview %></td></tr>
</table>
<br>

<table id="new_table" border="0">
  <tr><td><font color="blue">ニュースフィード</font></td></tr>
</table>
<table id="new_table" border="1" style="height:150px;">
  <tr><td>&nbsp;</td></tr>
</table>
<br>

app/views/items/index.html.erb
# encoding: utf-8

<font size="7" color="blue">商談一覧</font>
<br>
<br>

<% @items.each do |item| %>
<table id="index_table" border="0">
  <tr>
    <td>
      <%= link_to "* #{item.title} [確度：#{item.reliability}]", edit_item_path(item) %>
    </td>
  </tr>
</table>
<% end %>

<br>
<br>
<%= link_to '新規商談登録', new_item_path  %>

app/views/items/new.html.erb
# encoding: utf-8

<%= form_for @item do |f| %>

<table id="new_table" border="0">
  <tr>
    <th>タイトル</th>
    <td><%= f.text_field :title %></td>
  </tr>

  <tr>
    <th>概要</th>
    <td><%= f.text_area :overview, :rows =>5 %></td>
  </tr>

  <tr>
    <th>確度</th>
    <td><%= f.select :reliability, {"A" =>"A", "B" =>"B", "C" =>"C"} %></td>
  </tr>

  <tr>
    <th>&nbsp;</th>
    <td style="text-align: center;">&nbsp;</td>
  </tr>

</table>

<%= f.submit '登録', :confirm =>'この内容で登録しますか？'  %>
<% end %>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Conversation</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="main"><%= yield %></div>

</body>
</html>